-- UPGRADE 12: tutup buku bulanan
CREATE TABLE IF NOT EXISTS closed_periods (
  period CHAR(7) NOT NULL PRIMARY KEY,
  closed_by INT UNSIGNED NOT NULL,
  closed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
