-- UPGRADE 11: stok barang + invoice
CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  business_id INT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  sku VARCHAR(64) NULL,
  unit VARCHAR(24) NOT NULL DEFAULT 'pcs',
  cost_price DECIMAL(16,2) NOT NULL DEFAULT 0,
  sell_price DECIMAL(16,2) NOT NULL DEFAULT 0,
  stock DECIMAL(16,2) NOT NULL DEFAULT 0,
  min_stock DECIMAL(16,2) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_prod_biz (business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_moves (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT UNSIGNED NOT NULL,
  tx_id BIGINT UNSIGNED NULL,
  direction ENUM('in','out') NOT NULL,
  qty DECIMAL(16,2) NOT NULL,
  note VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sm_prod FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  business_id INT UNSIGNED NULL,
  number VARCHAR(40) NOT NULL UNIQUE,
  customer_name VARCHAR(128) NOT NULL,
  amount DECIMAL(16,2) NOT NULL,
  description VARCHAR(500) NULL,
  status ENUM('unpaid','paid','void') NOT NULL DEFAULT 'unpaid',
  tx_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
